/**
 * Types for the system notification framework.
 *
 * System notifications are sent for configurable events (e.g. user login,
 * backup completion) through user-selected notification channels
 * (Email, Discord, etc.).
 */

/** All supported system notification event types */
export const NOTIFICATION_EVENTS = {
  USER_LOGIN: "user_login",
  USER_CREATED: "user_created",
  BACKUP_SUCCESS: "backup_success",
  BACKUP_PARTIAL: "backup_partial",
  BACKUP_FAILURE: "backup_failure",
  RESTORE_COMPLETE: "restore_complete",
  RESTORE_FAILURE: "restore_failure",
  CONFIG_BACKUP: "config_backup",
  SYSTEM_ERROR: "system_error",
  STORAGE_USAGE_SPIKE: "storage_usage_spike",
  STORAGE_LIMIT_WARNING: "storage_limit_warning",
  STORAGE_MISSING_BACKUP: "storage_missing_backup",
  AIRGAP_SKIPPED: "airgap_skipped",
  UPDATE_AVAILABLE: "update_available",
  CONNECTION_OFFLINE: "connection_offline",
  CONNECTION_ONLINE: "connection_online",
  DB_VERSION_CHANGED: "db_version_changed",
  INTEGRITY_CHECK_FAILURE: "integrity_check_failure",
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

/**
 * Controls who receives a notification for user-specific events.
 * - "none"  – Only configured channels (admin channels)
 * - "also"  – Configured channels AND a direct email to the user
 * - "only"  – Only a direct email to the user (no admin channels)
 */
export type NotifyUserMode = "none" | "also" | "only";

/** Metadata describing a notification event */
export interface NotificationEventDefinition {
  id: NotificationEventType;
  name: string;
  description: string;
  category: "auth" | "backup" | "restore" | "system" | "storage" | "updates" | "health";
  /** Default enabled state when first configured */
  defaultEnabled: boolean;
  /**
   * When true, this event carries a user email address and can send
   * a direct notification to the affected user (only via Email/SMTP adapters).
   */
  supportsNotifyUser?: boolean;
  /**
   * When true, this event supports configurable reminder intervals.
   * The notification will be re-sent after the configured interval while the condition persists.
   */
  supportsReminder?: boolean;
  /** How often it reminds while nothing else is set, for an event with reminders. */
  defaultReminderHours?: number;
}

/** The color of the banner of a mail, the status tokens of the app. */
export type NotificationTone = "success" | "failure" | "warning" | "neutral";

/** The pictures a mail can show in its banner and on its buttons, by their lucide names. */
export type NotificationIcon =
  | "circle-check" | "circle-x" | "triangle-alert" | "unplug" | "plug" | "hard-drive" | "trending-up"
  | "clock-alert" | "circle-arrow-up" | "shield-alert" | "log-in" | "user-round-plus" | "mail" | "file-cog"
  | "history" | "calendar-clock" | "database" | "settings" | "user-round" | "users" | "external-link" | "archive";

/** A link into DBackup, or out of it like the release notes. */
export interface NotificationAction {
  label: string;
  /** A path of the app like `/dashboard/jobs?job=1`, made absolute with the address of the instance, or a full URL. */
  href: string;
  icon: NotificationIcon;
}

/** A destination of a run, one row of the mail. */
export interface NotificationDestination {
  name: string;
  adapterId: string;
  state: "ok" | "failed" | "skipped";
  /** Uploaded, Upload failed, Not connected. */
  detail: string;
  /** The message of a failed upload as it was written. */
  error?: string;
}

/** What went wrong, in plain words and as it was written. */
export interface NotificationProblem {
  title: string;
  help?: string;
  raw: string;
  /** The step and the time, like "Dump · 02:00:04". */
  where?: string;
}

/** Payload generated by a template for adapter consumption */
export interface NotificationPayload {
  /** Short title (email subject, embed title, etc.) */
  title: string;
  /** Plain text message body */
  message: string;
  /** Structured fields for rich display (embeds, tables) */
  fields?: Array<{ name: string; value: string; inline?: boolean }>;
  /** Hex color for embeds / status indicators */
  color?: string;
  /** Whether the event represents a success or failure */
  success: boolean;
  /** A short label for the status, like "Offline", for the channels that show one. */
  badge?: string;

  // What a mail shows beyond the fields. Chat channels leave these out.

  /** The color of the banner. Without it, `success` decides. */
  tone?: NotificationTone;
  icon?: NotificationIcon;
  /** Up to four short values for the tiles of a mail, like Started and Duration. */
  stats?: Array<{ label: string; value: string }>;
  problem?: NotificationProblem;
  destinations?: NotificationDestination[];
  /** A bar of how full something is, in percent. */
  usage?: { percent: number; label: string; aside: string };
  /** The list of facts under the tiles. Without it, the fields the tiles do not show. */
  details?: Array<{ name: string; value: string }>;
  /** A word to the reader in a box, like what to do about a sign-in that was not theirs. */
  note?: string;
  actions?: NotificationAction[];
  /** The line a mail client shows after the subject. */
  preheader?: string;
  /** Why the reader gets this and where it changes, set by whoever sends it. */
  reason?: string;
  /** When it happened, as ISO. */
  timestamp?: string;
}

/** What a template needs beyond the data of its event. */
export interface TemplateOptions {
  /** The time zone of the instance, `system.timezone`, which every time in the text uses. */
  timeZone?: string;
  /** "user" for the mail to the person a sign-in or a new account is about. */
  audience?: "channel" | "user";
}

/** Data passed to template functions per event type */
export interface UserLoginData {
  userName: string;
  email: string;
  ipAddress?: string;
  userAgent?: string;
  timestamp: string;
}

export interface UserCreatedData {
  userName: string;
  email: string;
  createdBy?: string;
  timestamp: string;
}

export interface BackupResultData {
  jobName: string;
  jobId?: string;
  sourceName?: string;
  /** The type of the source, like PostgreSQL. */
  sourceType?: string;
  duration?: number;
  size?: number;
  error?: string;
  executionId?: string;
  timestamp: string;
  startedAt?: string;
  /** Who started the run, as the execution stores it: Scheduler, Manual or Api. */
  trigger?: string;
  /** How many databases the run dumped. */
  databases?: number;
  /** The name of the encryption key, when the backup is encrypted. */
  encryptionKey?: string;
  destinations?: NotificationDestination[];
  /** The first thing that went wrong, from the log of the run. */
  problem?: NotificationProblem;
  /** The failed runs of the job in a row, this one included. */
  failedInARow?: number;
  lastSuccessAt?: string;
}

export interface RestoreResultData {
  sourceName?: string;
  targetDatabase?: string;
  databaseType?: string;
  backupFile?: string;
  storageName?: string;
  size?: number;
  duration?: number;
  error?: string;
  executionId?: string;
  timestamp: string;
}

export interface ConfigBackupData {
  fileName?: string;
  size?: number;
  encrypted: boolean;
  timestamp: string;
}

export interface SystemErrorData {
  component: string;
  error: string;
  details?: string;
  timestamp: string;
}

export interface StorageUsageSpikeData {
  storageName: string;
  /** The connection of the destination, for the button that opens it. */
  storageId?: string;
  previousSize: number;
  currentSize: number;
  changePercent: number;
  timestamp: string;
}

export interface StorageLimitWarningData {
  storageName: string;
  storageId?: string;
  currentSize: number;
  limitSize: number;
  usagePercent: number;
  timestamp: string;
}

export interface StorageMissingBackupData {
  storageName: string;
  storageId?: string;
  lastBackupAt?: string;
  thresholdHours: number;
  hoursSinceLastBackup: number;
  timestamp: string;
}

/** A backup run left out an air-gapped destination that was not connected. */
export interface AirGapSkippedData {
  storageName: string;
  storageId?: string;
  jobName: string;
  jobId?: string;
  /** When it last answered a health check, while one it kept did. */
  lastConnectedAt?: string;
  timestamp: string;
}

export interface UpdateAvailableData {
  latestVersion: string;
  currentVersion: string;
  releaseUrl?: string;
  timestamp: string;
}

export interface ConnectionOfflineData {
  adapterName: string;
  adapterType: "database" | "storage";
  adapterId: string;
  /** The connection itself, for the button that opens it. */
  configId?: string;
  consecutiveFailures: number;
  lastError?: string;
  timestamp: string;
}

export interface ConnectionOnlineData {
  adapterName: string;
  adapterType: "database" | "storage";
  adapterId: string;
  configId?: string;
  downtime?: string;
  timestamp: string;
}

export interface DbVersionChangedData {
  sourceName: string;
  sourceId: string;
  adapterId: string;
  previousVersion: string | null;
  newVersion: string;
  edition?: string;
  timestamp: string;
  isDowngrade: boolean;
}

export interface IntegrityCheckFailureData {
  totalFiles: number;
  failed: number;
  passed: number;
  skipped: number;
  triggerType: "Scheduler" | "Manual" | "Api";
  errors: Array<{
    file: string;
    destination: string;
    expected: string;
    actual: string;
  }>;
}

/** Union of all event data types for type-safe template dispatch */
export type NotificationEventData =
  | { eventType: typeof NOTIFICATION_EVENTS.USER_LOGIN; data: UserLoginData }
  | { eventType: typeof NOTIFICATION_EVENTS.USER_CREATED; data: UserCreatedData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_SUCCESS; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_PARTIAL; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_FAILURE; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.RESTORE_COMPLETE; data: RestoreResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.RESTORE_FAILURE; data: RestoreResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONFIG_BACKUP; data: ConfigBackupData }
  | { eventType: typeof NOTIFICATION_EVENTS.SYSTEM_ERROR; data: SystemErrorData }
  | { eventType: typeof NOTIFICATION_EVENTS.STORAGE_USAGE_SPIKE; data: StorageUsageSpikeData }
  | { eventType: typeof NOTIFICATION_EVENTS.STORAGE_LIMIT_WARNING; data: StorageLimitWarningData }
  | { eventType: typeof NOTIFICATION_EVENTS.STORAGE_MISSING_BACKUP; data: StorageMissingBackupData }
  | { eventType: typeof NOTIFICATION_EVENTS.AIRGAP_SKIPPED; data: AirGapSkippedData }
  | { eventType: typeof NOTIFICATION_EVENTS.UPDATE_AVAILABLE; data: UpdateAvailableData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONNECTION_OFFLINE; data: ConnectionOfflineData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONNECTION_ONLINE; data: ConnectionOnlineData }
  | { eventType: typeof NOTIFICATION_EVENTS.DB_VERSION_CHANGED; data: DbVersionChangedData }
  | { eventType: typeof NOTIFICATION_EVENTS.INTEGRITY_CHECK_FAILURE; data: IntegrityCheckFailureData };

/** Persisted notification configuration (stored as JSON in SystemSetting) */
export interface SystemNotificationConfig {
  /** Default channel IDs (AdapterConfig IDs) used when event has no override */
  globalChannels: string[];
  /** Per-event settings */
  events: Record<
    string,
    {
      enabled: boolean;
      /** Override channels for this event. null = use globalChannels */
      channels: string[] | null;
      /** Whether to also/only send a direct email to the affected user */
      notifyUser?: NotifyUserMode;
      /** Reminder interval in hours. When set, re-sends notification after this period while condition persists. */
      reminderIntervalHours?: number | null;
    }
  >;
}
