import NextAuth from "next-auth"
import { PrismaAdapter } from "@auth/prisma-adapter"
import prisma from "@/lib/prisma"
import Credentials from "next-auth/providers/credentials"
import WebAuthn from "next-auth/providers/webauthn"
import { z } from "zod"
import bcrypt from "bcryptjs"
import { authConfig } from "./auth.config"
import { verifyTotpToken } from "@/lib/totp"

export const { handlers, auth, signIn, signOut } = NextAuth({
  ...authConfig,
  experimental: { enableWebAuthn: true },
  adapter: PrismaAdapter(prisma),
  session: { strategy: "jwt" },
  callbacks: {
    async jwt({ token, user }) {
        if (user) {
            token.id = user.id;
        }
        return token;
    },
    async session({ session, token }) {
        if (session.user && token.id) {
            session.user.id = token.id as string;
        }
        return session;
    }
  },
  providers: [
    WebAuthn,
    Credentials({
        async authorize(credentials) {
            const parsedCredentials = z
                .object({
                    email: z.string().email(),
                    password: z.string().min(6),
                    code: z.string().optional(),
                    twoFactorToken: z.string().optional()
                })
                .safeParse(credentials);

            if (parsedCredentials.success) {
                const { email, password, code, twoFactorToken } = parsedCredentials.data;
                const user = await prisma.user.findUnique({
                    where: { email }
                });

                if (!user ||!user.password) return null;

                const passwordsMatch = await bcrypt.compare(password, user.password);
                if (passwordsMatch) {
                    if (user.isTwoFactorEnabled) {
                         // Check Passkey Token (if provided)
                         // We rely on temporary token generated by server action verifyPasskeyFor2FA
                         if (twoFactorToken && user.tempToken && user.tempTokenExpires) {
                             if (twoFactorToken === user.tempToken && new Date() < user.tempTokenExpires) {
                                 // Valid Match!
                                 // Clear token
                                 await prisma.user.update({
                                     where: { id: user.id },
                                     data: { tempToken: null, tempTokenExpires: null }
                                 });
                                 return user;
                             }
                         }

                         // Check TOTP (if provided)
                         if (user.totpSecret && code) {
                             const isValidToken = verifyTotpToken(code, user.totpSecret);
                             if (isValidToken) {
                                 return user;
                             }
                             // If code provided but invalid -> return null
                             return null;
                         }

                         // If we are here, 2FA is enabled but no valid proof provided
                         throw new Error("2FA_REQUIRED");
                    }
                    return user;
                }
            }
            return null;
        }
    })
  ],
})
